services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Domain\Admin\Factory\AdminFactoryInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Admin\Factory\AdminFactory