services:
    _defaults:
        autowire: true
        public: false

    OxidEsales\EshopCommunity\Internal\Setup\Database\Service\DatabaseCreatorInterface:
        class: OxidEsales\EshopCommunity\Internal\Setup\Database\Service\DatabaseCreator

    OxidEsales\EshopCommunity\Internal\Setup\Database\Service\DatabaseInitiatorInterface:
        class: OxidEsales\EshopCommunity\Internal\Setup\Database\Service\DatabaseInitiator

    OxidEsales\EshopCommunity\Internal\Setup\Database\Service\DatabaseInstallerInterface:
        class: OxidEsales\EshopCommunity\Internal\Setup\Database\Service\DatabaseInstaller