services:
    _defaults:
        autowire: true
        public: false

    OxidEsales\EshopCommunity\Internal\Setup\Directory\Service\DirectoryValidatorInterface:
        class: OxidEsales\EshopCommunity\Internal\Setup\Directory\Service\DirectoryValidator